#
#
# Isso aqui provisiona uma VM com rede publica -- como se fosse
# um computador fisico com um ip fixo.
# 
# Exemplo de como colocar uma chave ssh 
# https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2
#
#

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network :public_network #, ip: "192.168.0.200"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = 'hadoop_slave1'
  end

  ssh_pub_key = File.readlines("/home/zembrzuski/.ssh/id_rsa.pub").first.strip

  config.vm.provision "shell", inline: <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
  SHELL

end
